apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-joark
  namespace: default
  labels:
    team: dusseldorf
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://k9-joark.nais.preprod.local
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
  webproxy: true
  env:
    - name: DOKARKIV_BASE_URL
      value: https://dokarkiv-q1.nais.preprod.local
    - name: NAIS_STS_DISCOVERY_ENDPOINT
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: AZURE_CLIENT_ID
      value: b32ae17c-0276-4006-9507-4ef49e0e5e20
    - name: AZURE_AUTHORIZED_CLIENTS
      value: a6aef297-b9c9-4cac-82be-060d4fa68bb8,74124a64-e145-4d48-afff-0a375794b87f,97378ce0-19c5-481c-9478-abfc8193c79c,964c53ec-5e81-4b30-9cf9-972e7b934403,bb79926c-e11f-45da-99dc-edee7ce5e437,3c90567a-a7e9-4f6f-8f76-fd3a2abd2cad,7d4734fb-4aa4-4131-b85b-2eedf4cb958b
    - name: AZURE_V1_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration
    - name: AZURE_V2_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: HENTE_DOKUMENT_SCOPES
      value: 97f0b1bc-6aa9-4d44-a3c7-60b4318fbec4/.default