apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
  accessPolicy:
    inbound:
      rules:
        - application: frisinn-prosessering
          namespace: dusseldorf
          cluster: {{environment}}-fss

        - application: omsorgspengerutbetalingsoknad-arbeidstaker-prosessering
          namespace: default
          cluster: {{environment}}-fss


        - application: omsorgspengerutbetalingsoknad-arbeidstaker-prosessering
          namespace: dusseldorf
          cluster: {{environment}}-fss

        - application: omsorgspengesoknad-prosessering
          namespace: dusseldorf
          cluster: {{environment}}-gcp

        - application: k9-ettersending-prosessering
          namespace: dusseldorf
          cluster: {{environment}}-gcp

        - application: pleiepengesoknad-prosessering
          namespace: dusseldorf
          cluster: {{environment}}-fss

        - application: omsorgspengerutbetalingsoknad-prosessering
          namespace: dusseldorf
          cluster: {{environment}}-gcp

        - application: omsorgspenger-midlertidig-alene-prosessering
          namespace: dusseldorf
          cluster: {{environment}}-gcp

        - application: omsorgsdager-melding-prosessering
          namespace: dusseldorf
          cluster: {{environment}}-gcp

        - application: omsorgsdager-aleneomsorg-prosessering
          namespace: dusseldorf
          cluster: {{environment}}-gcp

        - application: pleiepenger-livets-sluttfase-prosessering
          namespace: dusseldorf
          cluster: {{environment}}-gcp
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
  envFrom:
    - secret: {{app}}
