apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
  accessPolicy:
    outbound:
      rules:
        - application: k9-mellomlagring
    inbound:
      rules:
        - application: omsorgspengerutbetalingsoknad-arbeidstaker-prosessering
        - application: omsorgspengesoknad-prosessering
        - application: k9-ettersending-prosessering
        - application: pleiepengesoknad-prosessering
        - application: omsorgspengerutbetalingsoknad-prosessering
        - application: omsorgspenger-midlertidig-alene-prosessering
        - application: omsorgsdager-aleneomsorg-prosessering
        - application: pleiepenger-livets-sluttfase-prosessering
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
