apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-joark
  namespace: default
  labels:
    team: dusseldorf
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  ingresses:
    - https://k9-joark.nais.adeo.no
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
  webproxy: true
  env:
    - name: DOKARKIV_BASE_URL
      value: https://dokarkiv.nais.adeo.no
    - name: NAIS_STS_DISCOVERY_ENDPOINT
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    - name: AZURE_CLIENT_ID
      value: cb751642-883c-48d3-9f82-06cc72c3e4b9
    - name: AZURE_AUTHORIZED_CLIENTS
      value: 84ef0905-64b3-440b-8f6a-0d88ef81a0f0,d2946143-0276-40ab-993e-4f29f3720d63,05c01005-6ee2-4d9d-9cd6-735c014071b6,c3ec240c-fee9-4491-b526-092ef288adcd,6a6fa1ee-57f4-4e3b-ac13-d7afc3148794
    - name: AZURE_V1_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/.well-known/openid-configuration
    - name: AZURE_V2_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration
    - name: HENTE_DOKUMENT_SCOPES
      value: 0c5a6709-ba2a-42b7-bbfc-9b9f844e2ee2/.default
